version: '3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  sandbox:
    image: registry.cn-chengdu.aliyuncs.com/aliyun_pdh_space/judge-service:v1.0.0
    container_name: sandbox
    privileged: true
    restart: always
    ports:
      - "5050:5050"
      - "5051:5051"
    networks:
      - net

  db-service:
    container_name: db-service
    privileged: true
    build:
      context: ./app/db-service # 路径
      dockerfile: Dockerfile
    volumes:
      - /root/server/oj-server/backend/log/db-service:/app/log
      - /root/server/oj-server/backend/config:/app/config
    ports:
      - "9000"
    networks:
      - net
    command:
      - "--node_type:1"
      - "--node_id:1"
      - "--node_port:9000"

  judge-service:
    container_name: judge-service
    privileged: true
    build:
      context: ./app/judge-service
      dockerfile: Dockerfile
    volumes:
      - /root/server/oj-server/backend/log/judge-service:/app/log
      - /root/server/oj-server/backend/config:/app/config
    ports:
      - "9010"
    networks:
      - net
    command:
      - "--node_type:2"
      - "--node_id:1"
      - "--node_port:9010"
    depends_on: # 本地服务的依赖，控制启动先后顺序
      - db-service
      - sandbox
  
  question-service:
    container_name: question-service
    privileged: true
    build:
      context: ./app/question-service
      dockerfile: Dockerfile
    volumes:
      - /root/server/oj-server/backend/log/question-service:/app/log
      - /root/server/oj-server/backend/config:/app/config
    ports:
      - "9020:9020"
    networks:
      - net
    command:
      - "--node_type:3"
      - "--node_id:1"
      - "--node_port:9020"
    depends_on: # 本地服务的依赖，控制启动先后顺序
      - db-service
      - judge-service
