// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: problem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// “提交”状态枚举，如果没有查询到状态，就意味着最近没有提交题目or题目提交过期了
type SubmitState int32

const (
	SubmitState_UPStateNormal    SubmitState = 0 // 初始状态
	SubmitState_UPStateCompiling SubmitState = 1 // 正在编译
	SubmitState_UPStateJudging   SubmitState = 2 // 已编译成功，正在判题
	SubmitState_UPStateExited    SubmitState = 3 // 已退出 -> 如何查询到这个状态，意味着可以查询结果了
)

// Enum value maps for SubmitState.
var (
	SubmitState_name = map[int32]string{
		0: "UPStateNormal",
		1: "UPStateCompiling",
		2: "UPStateJudging",
		3: "UPStateExited",
	}
	SubmitState_value = map[string]int32{
		"UPStateNormal":    0,
		"UPStateCompiling": 1,
		"UPStateJudging":   2,
		"UPStateExited":    3,
	}
)

func (x SubmitState) Enum() *SubmitState {
	p := new(SubmitState)
	*p = x
	return p
}

func (x SubmitState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmitState) Descriptor() protoreflect.EnumDescriptor {
	return file_problem_proto_enumTypes[0].Descriptor()
}

func (SubmitState) Type() protoreflect.EnumType {
	return &file_problem_proto_enumTypes[0]
}

func (x SubmitState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmitState.Descriptor instead.
func (SubmitState) EnumDescriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{0}
}

// 题目基础信息
type Problem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateAt      int64                  `protobuf:"varint,2,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,3,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	DeleteAt      string                 `protobuf:"bytes,4,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Problem) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Problem) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *Problem) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

func (x *Problem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Problem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Problem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Problem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 题目配置信息
type ProblemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompileLimit  *Limit                 `protobuf:"bytes,2,opt,name=compile_limit,json=compileLimit,proto3" json:"compile_limit,omitempty"`
	RunLimit      *Limit                 `protobuf:"bytes,3,opt,name=run_limit,json=runLimit,proto3" json:"run_limit,omitempty"`
	TestCases     []*TestCase            `protobuf:"bytes,4,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemConfig) Reset() {
	*x = ProblemConfig{}
	mi := &file_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemConfig) ProtoMessage() {}

func (x *ProblemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemConfig.ProtoReflect.Descriptor instead.
func (*ProblemConfig) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{1}
}

func (x *ProblemConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProblemConfig) GetCompileLimit() *Limit {
	if x != nil {
		return x.CompileLimit
	}
	return nil
}

func (x *ProblemConfig) GetRunLimit() *Limit {
	if x != nil {
		return x.RunLimit
	}
	return nil
}

func (x *ProblemConfig) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuLimit      int64                  `protobuf:"varint,1,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`          // CPU时间限制，单位纳秒
	ClockLimit    int64                  `protobuf:"varint,2,opt,name=clock_limit,json=clockLimit,proto3" json:"clock_limit,omitempty"`    // 等待时间限制，单位纳秒 （通常为 cpuLimit 两倍）
	MemoryLimit   int64                  `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"` // 内存限制，单位 byte
	StackLimit    int64                  `protobuf:"varint,4,opt,name=stack_limit,json=stackLimit,proto3" json:"stack_limit,omitempty"`    // 栈内存限制，单位 byte
	ProcLimit     int64                  `protobuf:"varint,5,opt,name=proc_limit,json=procLimit,proto3" json:"proc_limit,omitempty"`       // 线程数量限制，默认50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_problem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{2}
}

func (x *Limit) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *Limit) GetClockLimit() int64 {
	if x != nil {
		return x.ClockLimit
	}
	return 0
}

func (x *Limit) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Limit) GetStackLimit() int64 {
	if x != nil {
		return x.StackLimit
	}
	return 0
}

func (x *Limit) GetProcLimit() int64 {
	if x != nil {
		return x.ProcLimit
	}
	return 0
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_problem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{3}
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// 题目服务->判题服务
type JudgeSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Uid           int64                  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ConfigUrl     string                 `protobuf:"bytes,6,opt,name=config_url,json=configUrl,proto3" json:"config_url,omitempty"`
	TaskId        string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	UserName      string                 `protobuf:"bytes,9,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProblemName   string                 `protobuf:"bytes,10,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeSubmission) Reset() {
	*x = JudgeSubmission{}
	mi := &file_problem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeSubmission) ProtoMessage() {}

func (x *JudgeSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeSubmission.ProtoReflect.Descriptor instead.
func (*JudgeSubmission) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{4}
}

func (x *JudgeSubmission) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *JudgeSubmission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JudgeSubmission) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *JudgeSubmission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JudgeSubmission) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *JudgeSubmission) GetConfigUrl() string {
	if x != nil {
		return x.ConfigUrl
	}
	return ""
}

func (x *JudgeSubmission) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JudgeSubmission) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *JudgeSubmission) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JudgeSubmission) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

// 判题服务->题目服务
type JudgeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*JudgeResultItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ProblemId     int64                  `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Lang          string                 `protobuf:"bytes,7,opt,name=lang,proto3" json:"lang,omitempty"`
	TaskId        string                 `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Level         int32                  `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	UserName      string                 `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProblemName   string                 `protobuf:"bytes,11,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResult) Reset() {
	*x = JudgeResult{}
	mi := &file_problem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResult) ProtoMessage() {}

func (x *JudgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResult.ProtoReflect.Descriptor instead.
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{5}
}

func (x *JudgeResult) GetItems() []*JudgeResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *JudgeResult) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *JudgeResult) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *JudgeResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JudgeResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JudgeResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JudgeResult) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *JudgeResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JudgeResult) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *JudgeResult) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JudgeResult) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

type JudgeResultItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api返回字段
	Status     string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"` // 详细错误信息
	ExitStatus int64  `protobuf:"varint,3,opt,name=exitStatus,proto3" json:"exitStatus,omitempty"`      // 程序返回值
	Time       int64  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                  // 程序运行 CPU 时间，单位纳秒
	Memory     int64  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`              // 程序运行内存，单位 byte
	RunTime    int64  `protobuf:"varint,6,opt,name=runTime,proto3" json:"runTime,omitempty"`            // 程序运行现实时间，单位纳秒
	// 其他字段
	Content       string    `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	TestCase      *TestCase `protobuf:"bytes,8,opt,name=testCase,proto3" json:"testCase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResultItem) Reset() {
	*x = JudgeResultItem{}
	mi := &file_problem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResultItem) ProtoMessage() {}

func (x *JudgeResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResultItem.ProtoReflect.Descriptor instead.
func (*JudgeResultItem) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{6}
}

func (x *JudgeResultItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JudgeResultItem) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *JudgeResultItem) GetExitStatus() int64 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

func (x *JudgeResultItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *JudgeResultItem) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *JudgeResultItem) GetRunTime() int64 {
	if x != nil {
		return x.RunTime
	}
	return 0
}

func (x *JudgeResultItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *JudgeResultItem) GetTestCase() *TestCase {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type JudgeResultStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*JudgeResultItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResultStore) Reset() {
	*x = JudgeResultStore{}
	mi := &file_problem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResultStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResultStore) ProtoMessage() {}

func (x *JudgeResultStore) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResultStore.ProtoReflect.Descriptor instead.
func (*JudgeResultStore) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{7}
}

func (x *JudgeResultStore) GetItems() []*JudgeResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_problem_proto protoreflect.FileDescriptor

const file_problem_proto_rawDesc = "" +
	"\n" +
	"\rproblem.proto\"\xea\x01\n" +
	"\aProblem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcreate_at\x18\x02 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\x03 \x01(\x03R\bupdateAt\x12\x1b\n" +
	"\tdelete_at\x18\x04 \x01(\tR\bdeleteAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\x9b\x01\n" +
	"\rProblemConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\rcompile_limit\x18\x02 \x01(\v2\x06.LimitR\fcompileLimit\x12#\n" +
	"\trun_limit\x18\x03 \x01(\v2\x06.LimitR\brunLimit\x12(\n" +
	"\n" +
	"test_cases\x18\x04 \x03(\v2\t.TestCaseR\ttestCases\"\xa8\x01\n" +
	"\x05Limit\x12\x1b\n" +
	"\tcpu_limit\x18\x01 \x01(\x03R\bcpuLimit\x12\x1f\n" +
	"\vclock_limit\x18\x02 \x01(\x03R\n" +
	"clockLimit\x12!\n" +
	"\fmemory_limit\x18\x03 \x01(\x03R\vmemoryLimit\x12\x1f\n" +
	"\vstack_limit\x18\x04 \x01(\x03R\n" +
	"stackLimit\x12\x1d\n" +
	"\n" +
	"proc_limit\x18\x05 \x01(\x03R\tprocLimit\"8\n" +
	"\bTestCase\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\x8e\x02\n" +
	"\x0fJudgeSubmission\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x03R\x03uid\x12\x1d\n" +
	"\n" +
	"config_url\x18\x06 \x01(\tR\tconfigUrl\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12\x1b\n" +
	"\tuser_name\x18\t \x01(\tR\buserName\x12!\n" +
	"\fproblem_name\x18\n" +
	" \x01(\tR\vproblemName\"\xb3\x02\n" +
	"\vJudgeResult\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.JudgeResultItemR\x05items\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\x03R\tproblemId\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x12\n" +
	"\x04lang\x18\a \x01(\tR\x04lang\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\x12\x14\n" +
	"\x05level\x18\t \x01(\x05R\x05level\x12\x1b\n" +
	"\tuser_name\x18\n" +
	" \x01(\tR\buserName\x12!\n" +
	"\fproblem_name\x18\v \x01(\tR\vproblemName\"\xe9\x01\n" +
	"\x0fJudgeResultItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12\x1e\n" +
	"\n" +
	"exitStatus\x18\x03 \x01(\x03R\n" +
	"exitStatus\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x18\n" +
	"\arunTime\x18\x06 \x01(\x03R\arunTime\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12%\n" +
	"\btestCase\x18\b \x01(\v2\t.TestCaseR\btestCase\":\n" +
	"\x10JudgeResultStore\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.JudgeResultItemR\x05items*]\n" +
	"\vSubmitState\x12\x11\n" +
	"\rUPStateNormal\x10\x00\x12\x14\n" +
	"\x10UPStateCompiling\x10\x01\x12\x12\n" +
	"\x0eUPStateJudging\x10\x02\x12\x11\n" +
	"\rUPStateExited\x10\x03B\aZ\x05./;pbb\x06proto3"

var (
	file_problem_proto_rawDescOnce sync.Once
	file_problem_proto_rawDescData []byte
)

func file_problem_proto_rawDescGZIP() []byte {
	file_problem_proto_rawDescOnce.Do(func() {
		file_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_problem_proto_rawDesc), len(file_problem_proto_rawDesc)))
	})
	return file_problem_proto_rawDescData
}

var file_problem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_problem_proto_goTypes = []any{
	(SubmitState)(0),         // 0: SubmitState
	(*Problem)(nil),          // 1: Problem
	(*ProblemConfig)(nil),    // 2: ProblemConfig
	(*Limit)(nil),            // 3: Limit
	(*TestCase)(nil),         // 4: TestCase
	(*JudgeSubmission)(nil),  // 5: JudgeSubmission
	(*JudgeResult)(nil),      // 6: JudgeResult
	(*JudgeResultItem)(nil),  // 7: JudgeResultItem
	(*JudgeResultStore)(nil), // 8: JudgeResultStore
}
var file_problem_proto_depIdxs = []int32{
	3, // 0: ProblemConfig.compile_limit:type_name -> Limit
	3, // 1: ProblemConfig.run_limit:type_name -> Limit
	4, // 2: ProblemConfig.test_cases:type_name -> TestCase
	7, // 3: JudgeResult.items:type_name -> JudgeResultItem
	4, // 4: JudgeResultItem.testCase:type_name -> TestCase
	7, // 5: JudgeResultStore.items:type_name -> JudgeResultItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_problem_proto_init() }
func file_problem_proto_init() {
	if File_problem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_problem_proto_rawDesc), len(file_problem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_problem_proto_goTypes,
		DependencyIndexes: file_problem_proto_depIdxs,
		EnumInfos:         file_problem_proto_enumTypes,
		MessageInfos:      file_problem_proto_msgTypes,
	}.Build()
	File_problem_proto = out.File
	file_problem_proto_goTypes = nil
	file_problem_proto_depIdxs = nil
}
