// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.0
// source: problem_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ProblemService_CreateProblem_FullMethodName    = "/ProblemService/CreateProblem"
	ProblemService_UploadConfig_FullMethodName     = "/ProblemService/UploadConfig"
	ProblemService_PublishProblem_FullMethodName   = "/ProblemService/PublishProblem"
	ProblemService_UpdateProblem_FullMethodName    = "/ProblemService/UpdateProblem"
	ProblemService_DeleteProblem_FullMethodName    = "/ProblemService/DeleteProblem"
	ProblemService_GetTagList_FullMethodName       = "/ProblemService/GetTagList"
	ProblemService_GetProblemList_FullMethodName   = "/ProblemService/GetProblemList"
	ProblemService_GetProblemDetail_FullMethodName = "/ProblemService/GetProblemDetail"
	ProblemService_GetProblemConfig_FullMethodName = "/ProblemService/GetProblemConfig"
	ProblemService_SubmitProblem_FullMethodName    = "/ProblemService/SubmitProblem"
)

// ProblemServiceClient is the client API for ProblemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 题目服务接口
type ProblemServiceClient interface {
	// 新增题目
	CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error)
	// 上传配置文件
	UploadConfig(ctx context.Context, opts ...grpc.CallOption) (ProblemService_UploadConfigClient, error)
	// 发布题目
	PublishProblem(ctx context.Context, in *PublishProblemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新题目信息
	UpdateProblem(ctx context.Context, in *UpdateProblemRequest, opts ...grpc.CallOption) (*UpdateProblemResponse, error)
	// 删除题目
	DeleteProblem(ctx context.Context, in *DeleteProblemRequest, opts ...grpc.CallOption) (*DeleteProblemResponse, error)
	// 获取tag列表
	GetTagList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTagListResponse, error)
	// 获取题目列表
	GetProblemList(ctx context.Context, in *GetProblemListRequest, opts ...grpc.CallOption) (*GetProblemListResponse, error)
	// 查询题目详情
	GetProblemDetail(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error)
	// 获取题目配置
	GetProblemConfig(ctx context.Context, in *GetProblemConfigRequest, opts ...grpc.CallOption) (*GetProblemConfigResponse, error)
	// 提交
	SubmitProblem(ctx context.Context, in *SubmitProblemRequest, opts ...grpc.CallOption) (*SubmitProblemResponse, error)
}

type problemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemServiceClient(cc grpc.ClientConnInterface) ProblemServiceClient {
	return &problemServiceClient{cc}
}

func (c *problemServiceClient) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProblemResponse)
	err := c.cc.Invoke(ctx, ProblemService_CreateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) UploadConfig(ctx context.Context, opts ...grpc.CallOption) (ProblemService_UploadConfigClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProblemService_ServiceDesc.Streams[0], ProblemService_UploadConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &problemServiceUploadConfigClient{ClientStream: stream}
	return x, nil
}

type ProblemService_UploadConfigClient interface {
	Send(*UploadConfigFileChunk) error
	CloseAndRecv() (*UploadConfigResponse, error)
	grpc.ClientStream
}

type problemServiceUploadConfigClient struct {
	grpc.ClientStream
}

func (x *problemServiceUploadConfigClient) Send(m *UploadConfigFileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *problemServiceUploadConfigClient) CloseAndRecv() (*UploadConfigResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadConfigResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *problemServiceClient) PublishProblem(ctx context.Context, in *PublishProblemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProblemService_PublishProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) UpdateProblem(ctx context.Context, in *UpdateProblemRequest, opts ...grpc.CallOption) (*UpdateProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProblemResponse)
	err := c.cc.Invoke(ctx, ProblemService_UpdateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) DeleteProblem(ctx context.Context, in *DeleteProblemRequest, opts ...grpc.CallOption) (*DeleteProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProblemResponse)
	err := c.cc.Invoke(ctx, ProblemService_DeleteProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetTagList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagListResponse)
	err := c.cc.Invoke(ctx, ProblemService_GetTagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetProblemList(ctx context.Context, in *GetProblemListRequest, opts ...grpc.CallOption) (*GetProblemListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemListResponse)
	err := c.cc.Invoke(ctx, ProblemService_GetProblemList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetProblemDetail(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemResponse)
	err := c.cc.Invoke(ctx, ProblemService_GetProblemDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) GetProblemConfig(ctx context.Context, in *GetProblemConfigRequest, opts ...grpc.CallOption) (*GetProblemConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemConfigResponse)
	err := c.cc.Invoke(ctx, ProblemService_GetProblemConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemServiceClient) SubmitProblem(ctx context.Context, in *SubmitProblemRequest, opts ...grpc.CallOption) (*SubmitProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProblemResponse)
	err := c.cc.Invoke(ctx, ProblemService_SubmitProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServiceServer is the server API for ProblemService service.
// All implementations must embed UnimplementedProblemServiceServer
// for forward compatibility
//
// 题目服务接口
type ProblemServiceServer interface {
	// 新增题目
	CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error)
	// 上传配置文件
	UploadConfig(ProblemService_UploadConfigServer) error
	// 发布题目
	PublishProblem(context.Context, *PublishProblemRequest) (*emptypb.Empty, error)
	// 更新题目信息
	UpdateProblem(context.Context, *UpdateProblemRequest) (*UpdateProblemResponse, error)
	// 删除题目
	DeleteProblem(context.Context, *DeleteProblemRequest) (*DeleteProblemResponse, error)
	// 获取tag列表
	GetTagList(context.Context, *emptypb.Empty) (*GetTagListResponse, error)
	// 获取题目列表
	GetProblemList(context.Context, *GetProblemListRequest) (*GetProblemListResponse, error)
	// 查询题目详情
	GetProblemDetail(context.Context, *GetProblemRequest) (*GetProblemResponse, error)
	// 获取题目配置
	GetProblemConfig(context.Context, *GetProblemConfigRequest) (*GetProblemConfigResponse, error)
	// 提交
	SubmitProblem(context.Context, *SubmitProblemRequest) (*SubmitProblemResponse, error)
	mustEmbedUnimplementedProblemServiceServer()
}

// UnimplementedProblemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProblemServiceServer struct {
}

func (UnimplementedProblemServiceServer) CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblem not implemented")
}
func (UnimplementedProblemServiceServer) UploadConfig(ProblemService_UploadConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadConfig not implemented")
}
func (UnimplementedProblemServiceServer) PublishProblem(context.Context, *PublishProblemRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishProblem not implemented")
}
func (UnimplementedProblemServiceServer) UpdateProblem(context.Context, *UpdateProblemRequest) (*UpdateProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProblem not implemented")
}
func (UnimplementedProblemServiceServer) DeleteProblem(context.Context, *DeleteProblemRequest) (*DeleteProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProblem not implemented")
}
func (UnimplementedProblemServiceServer) GetTagList(context.Context, *emptypb.Empty) (*GetTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagList not implemented")
}
func (UnimplementedProblemServiceServer) GetProblemList(context.Context, *GetProblemListRequest) (*GetProblemListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemList not implemented")
}
func (UnimplementedProblemServiceServer) GetProblemDetail(context.Context, *GetProblemRequest) (*GetProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemDetail not implemented")
}
func (UnimplementedProblemServiceServer) GetProblemConfig(context.Context, *GetProblemConfigRequest) (*GetProblemConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemConfig not implemented")
}
func (UnimplementedProblemServiceServer) SubmitProblem(context.Context, *SubmitProblemRequest) (*SubmitProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProblem not implemented")
}
func (UnimplementedProblemServiceServer) mustEmbedUnimplementedProblemServiceServer() {}

// UnsafeProblemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServiceServer will
// result in compilation errors.
type UnsafeProblemServiceServer interface {
	mustEmbedUnimplementedProblemServiceServer()
}

func RegisterProblemServiceServer(s grpc.ServiceRegistrar, srv ProblemServiceServer) {
	s.RegisterService(&ProblemService_ServiceDesc, srv)
}

func _ProblemService_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_CreateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).CreateProblem(ctx, req.(*CreateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_UploadConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProblemServiceServer).UploadConfig(&problemServiceUploadConfigServer{ServerStream: stream})
}

type ProblemService_UploadConfigServer interface {
	SendAndClose(*UploadConfigResponse) error
	Recv() (*UploadConfigFileChunk, error)
	grpc.ServerStream
}

type problemServiceUploadConfigServer struct {
	grpc.ServerStream
}

func (x *problemServiceUploadConfigServer) SendAndClose(m *UploadConfigResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *problemServiceUploadConfigServer) Recv() (*UploadConfigFileChunk, error) {
	m := new(UploadConfigFileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProblemService_PublishProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).PublishProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_PublishProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).PublishProblem(ctx, req.(*PublishProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_UpdateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).UpdateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_UpdateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).UpdateProblem(ctx, req.(*UpdateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_DeleteProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).DeleteProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_DeleteProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).DeleteProblem(ctx, req.(*DeleteProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_GetTagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetTagList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetProblemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetProblemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_GetProblemList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetProblemList(ctx, req.(*GetProblemListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetProblemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetProblemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_GetProblemDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetProblemDetail(ctx, req.(*GetProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_GetProblemConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).GetProblemConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_GetProblemConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).GetProblemConfig(ctx, req.(*GetProblemConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemService_SubmitProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServiceServer).SubmitProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemService_SubmitProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServiceServer).SubmitProblem(ctx, req.(*SubmitProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProblemService_ServiceDesc is the grpc.ServiceDesc for ProblemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProblemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProblemService",
	HandlerType: (*ProblemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblem",
			Handler:    _ProblemService_CreateProblem_Handler,
		},
		{
			MethodName: "PublishProblem",
			Handler:    _ProblemService_PublishProblem_Handler,
		},
		{
			MethodName: "UpdateProblem",
			Handler:    _ProblemService_UpdateProblem_Handler,
		},
		{
			MethodName: "DeleteProblem",
			Handler:    _ProblemService_DeleteProblem_Handler,
		},
		{
			MethodName: "GetTagList",
			Handler:    _ProblemService_GetTagList_Handler,
		},
		{
			MethodName: "GetProblemList",
			Handler:    _ProblemService_GetProblemList_Handler,
		},
		{
			MethodName: "GetProblemDetail",
			Handler:    _ProblemService_GetProblemDetail_Handler,
		},
		{
			MethodName: "GetProblemConfig",
			Handler:    _ProblemService_GetProblemConfig_Handler,
		},
		{
			MethodName: "SubmitProblem",
			Handler:    _ProblemService_SubmitProblem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadConfig",
			Handler:       _ProblemService_UploadConfig_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "problem_service.proto",
}
