// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: problem_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增题目
type CreateProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProblemRequest) Reset() {
	*x = CreateProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProblemRequest) ProtoMessage() {}

func (x *CreateProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProblemRequest.ProtoReflect.Descriptor instead.
func (*CreateProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProblemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProblemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProblemRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateProblemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProblemResponse) Reset() {
	*x = CreateProblemResponse{}
	mi := &file_problem_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProblemResponse) ProtoMessage() {}

func (x *CreateProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProblemResponse.ProtoReflect.Descriptor instead.
func (*CreateProblemResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProblemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 上传配置文件
type UploadConfigFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 文件分片内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigFileChunk) Reset() {
	*x = UploadConfigFileChunk{}
	mi := &file_problem_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigFileChunk) ProtoMessage() {}

func (x *UploadConfigFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigFileChunk.ProtoReflect.Descriptor instead.
func (*UploadConfigFileChunk) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadConfigFileChunk) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *UploadConfigFileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // 服务端最终存储路径
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                        // 文件大小(字节)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigResponse) Reset() {
	*x = UploadConfigResponse{}
	mi := &file_problem_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigResponse) ProtoMessage() {}

func (x *UploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigResponse.ProtoReflect.Descriptor instead.
func (*UploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadConfigResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadConfigResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 发布题目
type PublishProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProblemRequest) Reset() {
	*x = PublishProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProblemRequest) ProtoMessage() {}

func (x *PublishProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProblemRequest.ProtoReflect.Descriptor instead.
func (*PublishProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{4}
}

func (x *PublishProblemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新题目
type UpdateProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Problem               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProblemRequest) Reset() {
	*x = UpdateProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProblemRequest) ProtoMessage() {}

func (x *UpdateProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProblemRequest.ProtoReflect.Descriptor instead.
func (*UpdateProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProblemRequest) GetData() *Problem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProblemResponse) Reset() {
	*x = UpdateProblemResponse{}
	mi := &file_problem_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProblemResponse) ProtoMessage() {}

func (x *UpdateProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProblemResponse.ProtoReflect.Descriptor instead.
func (*UpdateProblemResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProblemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProblemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除题目
type DeleteProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProblemRequest) Reset() {
	*x = DeleteProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProblemRequest) ProtoMessage() {}

func (x *DeleteProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProblemRequest.ProtoReflect.Descriptor instead.
func (*DeleteProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProblemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProblemResponse) Reset() {
	*x = DeleteProblemResponse{}
	mi := &file_problem_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProblemResponse) ProtoMessage() {}

func (x *DeleteProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProblemResponse.ProtoReflect.Descriptor instead.
func (*DeleteProblemResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProblemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询题目列表
// 使用偏移量分页
type GetProblemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemListRequest) Reset() {
	*x = GetProblemListRequest{}
	mi := &file_problem_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemListRequest) ProtoMessage() {}

func (x *GetProblemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemListRequest.ProtoReflect.Descriptor instead.
func (*GetProblemListRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetProblemListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProblemListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetProblemListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetProblemListRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetProblemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*Problem             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemListResponse) Reset() {
	*x = GetProblemListResponse{}
	mi := &file_problem_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemListResponse) ProtoMessage() {}

func (x *GetProblemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemListResponse.ProtoReflect.Descriptor instead.
func (*GetProblemListResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProblemListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetProblemListResponse) GetData() []*Problem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取题目详情
type GetProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemRequest) Reset() {
	*x = GetProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemRequest) ProtoMessage() {}

func (x *GetProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemRequest.ProtoReflect.Descriptor instead.
func (*GetProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetProblemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problem       *Problem               `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemResponse) Reset() {
	*x = GetProblemResponse{}
	mi := &file_problem_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemResponse) ProtoMessage() {}

func (x *GetProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemResponse.ProtoReflect.Descriptor instead.
func (*GetProblemResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetProblemResponse) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

// 获取题目配置
type GetProblemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemConfigRequest) Reset() {
	*x = GetProblemConfigRequest{}
	mi := &file_problem_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemConfigRequest) ProtoMessage() {}

func (x *GetProblemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemConfigRequest.ProtoReflect.Descriptor instead.
func (*GetProblemConfigRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetProblemConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProblemConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemConfig *ProblemConfig         `protobuf:"bytes,1,opt,name=problem_config,json=problemConfig,proto3" json:"problem_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemConfigResponse) Reset() {
	*x = GetProblemConfigResponse{}
	mi := &file_problem_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemConfigResponse) ProtoMessage() {}

func (x *GetProblemConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemConfigResponse.ProtoReflect.Descriptor instead.
func (*GetProblemConfigResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetProblemConfigResponse) GetProblemConfig() *ProblemConfig {
	if x != nil {
		return x.ProblemConfig
	}
	return nil
}

// tags
type GetTagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagListResponse) Reset() {
	*x = GetTagListResponse{}
	mi := &file_problem_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListResponse) ProtoMessage() {}

func (x *GetTagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListResponse.ProtoReflect.Descriptor instead.
func (*GetTagListResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTagListResponse) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 提交
type SubmitProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProblemRequest) Reset() {
	*x = SubmitProblemRequest{}
	mi := &file_problem_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProblemRequest) ProtoMessage() {}

func (x *SubmitProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProblemRequest.ProtoReflect.Descriptor instead.
func (*SubmitProblemRequest) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitProblemRequest) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *SubmitProblemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubmitProblemRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SubmitProblemRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SubmitProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProblemResponse) Reset() {
	*x = SubmitProblemResponse{}
	mi := &file_problem_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProblemResponse) ProtoMessage() {}

func (x *SubmitProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_problem_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProblemResponse.ProtoReflect.Descriptor instead.
func (*SubmitProblemResponse) Descriptor() ([]byte, []int) {
	return file_problem_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitProblemResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitProblemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_problem_service_proto protoreflect.FileDescriptor

const file_problem_service_proto_rawDesc = "" +
	"\n" +
	"\x15problem_service.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\rproblem.proto\"x\n" +
	"\x14CreateProblemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"'\n" +
	"\x15CreateProblemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"P\n" +
	"\x15UploadConfigFileChunk\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"G\n" +
	"\x14UploadConfigResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"'\n" +
	"\x15PublishProblemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x14UpdateProblemRequest\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\v2\b.ProblemR\x04data\"A\n" +
	"\x15UpdateProblemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x14DeleteProblemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x15DeleteProblemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"t\n" +
	"\x15GetProblemListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"L\n" +
	"\x16GetProblemListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\x04data\x18\x02 \x03(\v2\b.ProblemR\x04data\"#\n" +
	"\x11GetProblemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x12GetProblemResponse\x12\"\n" +
	"\aproblem\x18\x01 \x01(\v2\b.ProblemR\aproblem\")\n" +
	"\x17GetProblemConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x18GetProblemConfigResponse\x125\n" +
	"\x0eproblem_config\x18\x01 \x01(\v2\x0e.ProblemConfigR\rproblemConfig\"(\n" +
	"\x12GetTagListResponse\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data\"s\n" +
	"\x14SubmitProblemRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"J\n" +
	"\x15SubmitProblemResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe7\a\n" +
	"\x0eProblemService\x12a\n" +
	"\rCreateProblem\x12\x15.CreateProblemRequest\x1a\x16.CreateProblemResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/problem/create\x12i\n" +
	"\fUploadConfig\x12\x16.UploadConfigFileChunk\x1a\x15.UploadConfigResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/problem/upload_config(\x01\x12d\n" +
	"\x0ePublishProblem\x12\x16.PublishProblemRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/problem/publish\x12a\n" +
	"\rUpdateProblem\x12\x15.UpdateProblemRequest\x1a\x16.UpdateProblemResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/problem/update\x12W\n" +
	"\rDeleteProblem\x12\x15.DeleteProblemRequest\x1a\x16.DeleteProblemResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/v1/problem\x12[\n" +
	"\n" +
	"GetTagList\x12\x16.google.protobuf.Empty\x1a\x13.GetTagListResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/problem/tag_list\x12_\n" +
	"\x0eGetProblemList\x12\x16.GetProblemListRequest\x1a\x17.GetProblemListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/problem/list\x12[\n" +
	"\x10GetProblemDetail\x12\x12.GetProblemRequest\x1a\x13.GetProblemResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/problem/detail\x12g\n" +
	"\x10GetProblemConfig\x12\x18.GetProblemConfigRequest\x1a\x19.GetProblemConfigResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/problem/config\x12a\n" +
	"\rSubmitProblem\x12\x15.SubmitProblemRequest\x1a\x16.SubmitProblemResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/problem/submitB\aZ\x05./;pbb\x06proto3"

var (
	file_problem_service_proto_rawDescOnce sync.Once
	file_problem_service_proto_rawDescData []byte
)

func file_problem_service_proto_rawDescGZIP() []byte {
	file_problem_service_proto_rawDescOnce.Do(func() {
		file_problem_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_problem_service_proto_rawDesc), len(file_problem_service_proto_rawDesc)))
	})
	return file_problem_service_proto_rawDescData
}

var file_problem_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_problem_service_proto_goTypes = []any{
	(*CreateProblemRequest)(nil),     // 0: CreateProblemRequest
	(*CreateProblemResponse)(nil),    // 1: CreateProblemResponse
	(*UploadConfigFileChunk)(nil),    // 2: UploadConfigFileChunk
	(*UploadConfigResponse)(nil),     // 3: UploadConfigResponse
	(*PublishProblemRequest)(nil),    // 4: PublishProblemRequest
	(*UpdateProblemRequest)(nil),     // 5: UpdateProblemRequest
	(*UpdateProblemResponse)(nil),    // 6: UpdateProblemResponse
	(*DeleteProblemRequest)(nil),     // 7: DeleteProblemRequest
	(*DeleteProblemResponse)(nil),    // 8: DeleteProblemResponse
	(*GetProblemListRequest)(nil),    // 9: GetProblemListRequest
	(*GetProblemListResponse)(nil),   // 10: GetProblemListResponse
	(*GetProblemRequest)(nil),        // 11: GetProblemRequest
	(*GetProblemResponse)(nil),       // 12: GetProblemResponse
	(*GetProblemConfigRequest)(nil),  // 13: GetProblemConfigRequest
	(*GetProblemConfigResponse)(nil), // 14: GetProblemConfigResponse
	(*GetTagListResponse)(nil),       // 15: GetTagListResponse
	(*SubmitProblemRequest)(nil),     // 16: SubmitProblemRequest
	(*SubmitProblemResponse)(nil),    // 17: SubmitProblemResponse
	(*Problem)(nil),                  // 18: Problem
	(*ProblemConfig)(nil),            // 19: ProblemConfig
	(*emptypb.Empty)(nil),            // 20: google.protobuf.Empty
}
var file_problem_service_proto_depIdxs = []int32{
	18, // 0: UpdateProblemRequest.data:type_name -> Problem
	18, // 1: GetProblemListResponse.data:type_name -> Problem
	18, // 2: GetProblemResponse.problem:type_name -> Problem
	19, // 3: GetProblemConfigResponse.problem_config:type_name -> ProblemConfig
	0,  // 4: ProblemService.CreateProblem:input_type -> CreateProblemRequest
	2,  // 5: ProblemService.UploadConfig:input_type -> UploadConfigFileChunk
	4,  // 6: ProblemService.PublishProblem:input_type -> PublishProblemRequest
	5,  // 7: ProblemService.UpdateProblem:input_type -> UpdateProblemRequest
	7,  // 8: ProblemService.DeleteProblem:input_type -> DeleteProblemRequest
	20, // 9: ProblemService.GetTagList:input_type -> google.protobuf.Empty
	9,  // 10: ProblemService.GetProblemList:input_type -> GetProblemListRequest
	11, // 11: ProblemService.GetProblemDetail:input_type -> GetProblemRequest
	13, // 12: ProblemService.GetProblemConfig:input_type -> GetProblemConfigRequest
	16, // 13: ProblemService.SubmitProblem:input_type -> SubmitProblemRequest
	1,  // 14: ProblemService.CreateProblem:output_type -> CreateProblemResponse
	3,  // 15: ProblemService.UploadConfig:output_type -> UploadConfigResponse
	20, // 16: ProblemService.PublishProblem:output_type -> google.protobuf.Empty
	6,  // 17: ProblemService.UpdateProblem:output_type -> UpdateProblemResponse
	8,  // 18: ProblemService.DeleteProblem:output_type -> DeleteProblemResponse
	15, // 19: ProblemService.GetTagList:output_type -> GetTagListResponse
	10, // 20: ProblemService.GetProblemList:output_type -> GetProblemListResponse
	12, // 21: ProblemService.GetProblemDetail:output_type -> GetProblemResponse
	14, // 22: ProblemService.GetProblemConfig:output_type -> GetProblemConfigResponse
	17, // 23: ProblemService.SubmitProblem:output_type -> SubmitProblemResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_problem_service_proto_init() }
func file_problem_service_proto_init() {
	if File_problem_service_proto != nil {
		return
	}
	file_problem_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_problem_service_proto_rawDesc), len(file_problem_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_problem_service_proto_goTypes,
		DependencyIndexes: file_problem_service_proto_depIdxs,
		MessageInfos:      file_problem_service_proto_msgTypes,
	}.Build()
	File_problem_service_proto = out.File
	file_problem_service_proto_goTypes = nil
	file_problem_service_proto_depIdxs = nil
}
