// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: record_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 提交记录
type SubmitRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProblemId     int64                  `protobuf:"varint,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemName   string                 `protobuf:"bytes,3,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"` // []PBResult 二进制数据
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Lang          string                 `protobuf:"bytes,7,opt,name=lang,proto3" json:"lang,omitempty"`
	Id            int64                  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProblemLevel  int32                  `protobuf:"varint,10,opt,name=problem_level,json=problemLevel,proto3" json:"problem_level,omitempty"`
	UserName      string                 `protobuf:"bytes,11,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRecord) Reset() {
	*x = SubmitRecord{}
	mi := &file_record_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRecord) ProtoMessage() {}

func (x *SubmitRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRecord.ProtoReflect.Descriptor instead.
func (*SubmitRecord) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRecord) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SubmitRecord) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *SubmitRecord) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

func (x *SubmitRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitRecord) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SubmitRecord) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitRecord) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SubmitRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SubmitRecord) GetProblemLevel() int32 {
	if x != nil {
		return x.ProblemLevel
	}
	return 0
}

func (x *SubmitRecord) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// 查询提交记录列表 使用偏移量分页
type GetSubmitRecordListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmitRecordListRequest) Reset() {
	*x = GetSubmitRecordListRequest{}
	mi := &file_record_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmitRecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmitRecordListRequest) ProtoMessage() {}

func (x *GetSubmitRecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmitRecordListRequest.ProtoReflect.Descriptor instead.
func (*GetSubmitRecordListRequest) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubmitRecordListRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetSubmitRecordListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubmitRecordListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSubmitRecordListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*SubmitRecord        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmitRecordListResponse) Reset() {
	*x = GetSubmitRecordListResponse{}
	mi := &file_record_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmitRecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmitRecordListResponse) ProtoMessage() {}

func (x *GetSubmitRecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmitRecordListResponse.ProtoReflect.Descriptor instead.
func (*GetSubmitRecordListResponse) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubmitRecordListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSubmitRecordListResponse) GetData() []*SubmitRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查询提交记录详情
type GetSubmitRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmitRecordRequest) Reset() {
	*x = GetSubmitRecordRequest{}
	mi := &file_record_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmitRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmitRecordRequest) ProtoMessage() {}

func (x *GetSubmitRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmitRecordRequest.ProtoReflect.Descriptor instead.
func (*GetSubmitRecordRequest) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubmitRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSubmitRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SubmitRecord          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmitRecordResponse) Reset() {
	*x = GetSubmitRecordResponse{}
	mi := &file_record_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmitRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmitRecordResponse) ProtoMessage() {}

func (x *GetSubmitRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmitRecordResponse.ProtoReflect.Descriptor instead.
func (*GetSubmitRecordResponse) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubmitRecordResponse) GetData() *SubmitRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryJudgeResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJudgeResultRequest) Reset() {
	*x = QueryJudgeResultRequest{}
	mi := &file_record_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJudgeResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJudgeResultRequest) ProtoMessage() {}

func (x *QueryJudgeResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJudgeResultRequest.ProtoReflect.Descriptor instead.
func (*QueryJudgeResultRequest) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{5}
}

func (x *QueryJudgeResultRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type QueryJudgeResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJudgeResultResponse) Reset() {
	*x = QueryJudgeResultResponse{}
	mi := &file_record_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJudgeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJudgeResultResponse) ProtoMessage() {}

func (x *QueryJudgeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJudgeResultResponse.ProtoReflect.Descriptor instead.
func (*QueryJudgeResultResponse) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryJudgeResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryJudgeResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 排行榜数据
type LeaderboardUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Mobile        int64                  `protobuf:"varint,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardUserInfo) Reset() {
	*x = LeaderboardUserInfo{}
	mi := &file_record_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardUserInfo) ProtoMessage() {}

func (x *LeaderboardUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_record_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardUserInfo.ProtoReflect.Descriptor instead.
func (*LeaderboardUserInfo) Descriptor() ([]byte, []int) {
	return file_record_service_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardUserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LeaderboardUserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LeaderboardUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LeaderboardUserInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardUserInfo) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

var File_record_service_proto protoreflect.FileDescriptor

const file_record_service_proto_rawDesc = "" +
	"\n" +
	"\x14record_service.proto\"\xab\x02\n" +
	"\fSubmitRecord\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\x03R\tproblemId\x12!\n" +
	"\fproblem_name\x18\x03 \x01(\tR\vproblemName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x12\n" +
	"\x04lang\x18\a \x01(\tR\x04lang\x12\x0e\n" +
	"\x02id\x18\b \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12#\n" +
	"\rproblem_level\x18\n" +
	" \x01(\x05R\fproblemLevel\x12\x1b\n" +
	"\tuser_name\x18\v \x01(\tR\buserName\"_\n" +
	"\x1aGetSubmitRecordListRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x1bGetSubmitRecordListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.SubmitRecordR\x04data\"(\n" +
	"\x16GetSubmitRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x17GetSubmitRecordResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.SubmitRecordR\x04data\"2\n" +
	"\x17QueryJudgeResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"L\n" +
	"\x18QueryJudgeResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8a\x01\n" +
	"\x13LeaderboardUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\x03R\x06mobile2\xf4\x01\n" +
	"\rRecordService\x12P\n" +
	"\x13GetSubmitRecordList\x12\x1b.GetSubmitRecordListRequest\x1a\x1c.GetSubmitRecordListResponse\x12H\n" +
	"\x13GetSubmitRecordData\x12\x17.GetSubmitRecordRequest\x1a\x18.GetSubmitRecordResponse\x12G\n" +
	"\x10QueryJudgeResult\x12\x18.QueryJudgeResultRequest\x1a\x19.QueryJudgeResultResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_record_service_proto_rawDescOnce sync.Once
	file_record_service_proto_rawDescData []byte
)

func file_record_service_proto_rawDescGZIP() []byte {
	file_record_service_proto_rawDescOnce.Do(func() {
		file_record_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_service_proto_rawDesc), len(file_record_service_proto_rawDesc)))
	})
	return file_record_service_proto_rawDescData
}

var file_record_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_record_service_proto_goTypes = []any{
	(*SubmitRecord)(nil),                // 0: SubmitRecord
	(*GetSubmitRecordListRequest)(nil),  // 1: GetSubmitRecordListRequest
	(*GetSubmitRecordListResponse)(nil), // 2: GetSubmitRecordListResponse
	(*GetSubmitRecordRequest)(nil),      // 3: GetSubmitRecordRequest
	(*GetSubmitRecordResponse)(nil),     // 4: GetSubmitRecordResponse
	(*QueryJudgeResultRequest)(nil),     // 5: QueryJudgeResultRequest
	(*QueryJudgeResultResponse)(nil),    // 6: QueryJudgeResultResponse
	(*LeaderboardUserInfo)(nil),         // 7: LeaderboardUserInfo
}
var file_record_service_proto_depIdxs = []int32{
	0, // 0: GetSubmitRecordListResponse.data:type_name -> SubmitRecord
	0, // 1: GetSubmitRecordResponse.data:type_name -> SubmitRecord
	1, // 2: RecordService.GetSubmitRecordList:input_type -> GetSubmitRecordListRequest
	3, // 3: RecordService.GetSubmitRecordData:input_type -> GetSubmitRecordRequest
	5, // 4: RecordService.QueryJudgeResult:input_type -> QueryJudgeResultRequest
	2, // 5: RecordService.GetSubmitRecordList:output_type -> GetSubmitRecordListResponse
	4, // 6: RecordService.GetSubmitRecordData:output_type -> GetSubmitRecordResponse
	6, // 7: RecordService.QueryJudgeResult:output_type -> QueryJudgeResultResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_record_service_proto_init() }
func file_record_service_proto_init() {
	if File_record_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_service_proto_rawDesc), len(file_record_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_record_service_proto_goTypes,
		DependencyIndexes: file_record_service_proto_depIdxs,
		MessageInfos:      file_record_service_proto_msgTypes,
	}.Build()
	File_record_service_proto = out.File
	file_record_service_proto_goTypes = nil
	file_record_service_proto_depIdxs = nil
}
